version: "3.9"
services:

  #MySQL Service
  db:
    image: mysql:5.7.16
    container_name: laravel-10-boilerplate-db
    restart: unless-stopped
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: app-db1
      MYSQL_ROOT_PASSWORD: rootPassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Asia/Dhaka
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - private-network

  # PHP My Admin
  phpmyadmin:
    container_name: laravel-10-boilerplate-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "92:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootPassword
    networks:
      - private-network
      - external-network

  site:
    build: .
    container_name: laravel-10-boilerplate-web-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - private-network
      - external-network
    command: sh -c "composer update && chmod -R 777 . && apache2-foreground"

#Docker Networks
networks:
  private-network:
    name: laravel-10-boilerplate-ext
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
  external-network:
    name: laravel-10-boilerplate-int

#Volumes
volumes:
  mysql-data:
      